In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
# Read the csv file into a pandas DataFrame

performance = pd.read_csv('../data/samples.csv')
performance.head()

otu_id otu_label      2000      2001      2002      2003      2004  \
0       1       AXP  0.006869 -0.339676  0.000563  0.359279  0.171095   
1       2       CAT  0.002751  0.163384 -0.099845  0.851785  0.195363   
2       3       DIS  0.000113 -0.248466 -0.209897  0.401704  0.205888   
3       4        HD -0.331899  0.120603 -0.526192  0.478752  0.205863   
4       5       IBM -0.240567  0.438470 -0.352779  0.185081  0.069837   

       2005      2006      2007  ...      2010      2011      2012      2013  \
0  0.047010  0.185383 -0.143251  ...  0.070672  0.106434  0.206819  0.569791   
1  0.224479  0.076721  0.197358  ...  0.666731 -0.022303 -0.007904 -0.002906   
2 -0.128790  0.435979 -0.046332  ...  0.175764  0.010597  0.331345  0.522512   
3 -0.049030  0.012380 -0.330379  ...  0.240235  0.229130  0.490326  0.322462   
4 -0.161632  0.194059  0.128171  ...  0.140393  0.270309  0.043179 -0.014898   

       2014      2015      2016      2017      2018      2019  
0  0.034735 -0.243239  0.108990  0.347316 -0.030422  0.304835  
1  0.039185 -0.231932  0.444654  0.726567 -0.179165  0.204403  
2  0.254216  0.120639  0.025639  0.036984  0.022466  0.346565  
3  0.306183  0.283122  0.052467  0.435203 -0.076475  0.427053  
4 -0.122261 -0.118897  0.270549 -0.045640 -0.230799  0.257397  

[5 rows x 22 columns]

In [3]:
# Drop columns not needed

performance = performance.drop(['otu_id', 'otu_label'], axis=1)
performance

2000      2001      2002      2003      2004      2005      2006  \
0   0.006869 -0.339676  0.000563  0.359279  0.171095  0.047010  0.185383   
1   0.002751  0.163384 -0.099845  0.851785  0.195363  0.224479  0.076721   
2   0.000113 -0.248466 -0.209897  0.401704  0.205888 -0.128790  0.435979   
3  -0.331899  0.120603 -0.526192  0.478752  0.205863 -0.049030  0.012380   
4  -0.240567  0.438470 -0.352779  0.185081  0.069837 -0.161632  0.194059   
5  -0.277085  0.027439 -0.510107  1.008141 -0.272635  0.069775 -0.179676   
6   0.141905  0.151746 -0.075660 -0.030887  0.251665 -0.032509  0.106585   
7  -0.044133 -0.158802 -0.316161  0.503459  0.094612  0.044831  0.251573   
8   0.077278 -0.206370 -0.047961  0.172817 -0.161974 -0.012756  0.216498   
9  -0.128416 -0.210681 -0.384196  0.558968  0.308512  0.088604  0.323941   
10  0.286055  0.021827  0.074855  0.406301 -0.017198 -0.036295  0.026380   
11  0.388044 -0.356181 -0.018401 -0.128434 -0.317250  0.045254  0.395414   
12 -0.630400  0.501246 -0.224306  0.055847  0.080927 -0.012412  0.153892   
13 -0.259008  0.035282  0.109682  0.182587  0.126378  0.060791  0.125440   
14  0.274998 -0.158230 -0.028285  0.545048  0.106536  0.101640  0.125629   
15 -0.219444  0.089313 -0.119144  0.054353 -0.000555 -0.118553  0.010832   
16  0.117179 -0.073265 -0.088605  0.204296  0.279813  0.122900  0.384489   

        2007      2008      2009      2010      2011      2012      2013  \
0  -0.143251 -0.638984  1.258279  0.070672  0.106434  0.206819  0.569791   
1   0.197358 -0.368758  0.324359  0.666731 -0.022303 -0.007904 -0.002906   
2  -0.046332 -0.286749  0.432804  0.175764  0.010597  0.331345  0.522512   
3  -0.330379 -0.116666  0.301407  0.240235  0.229130  0.490326  0.322462   
4   0.128171 -0.214115  0.591181  0.140393  0.270309  0.043179 -0.014898   
5   0.329087 -0.426530  0.436096  0.042641  0.194452 -0.133559  0.275995   
6   0.034375 -0.075747  0.107210 -0.010431  0.085230  0.108091  0.328713   
7  -0.069744 -0.254906  0.340350  0.018913 -0.210544  0.329385  0.327490   
8   0.301206 -0.242728  0.298649  0.187011  0.092538  0.062393  0.148889   
9   0.385053  0.093072  0.036914  0.265408  0.340614 -0.101602  0.120984   
10  0.112934 -0.297260  0.484979  0.065313 -0.033445  0.138405  0.522675   
11  0.360145 -0.452670  0.264799  0.020802  0.087838  0.125887  0.240156   
12  0.206282 -0.446852  0.597338 -0.069591 -0.049975  0.034849  0.414239   
13  0.167226 -0.135784  0.014134  0.085053  0.069433  0.058312  0.223175   
14  0.242978 -0.285608  0.335965  0.148325 -0.055277  0.123817  0.394475   
15  0.028780  0.200502 -0.024381  0.026699  0.132393  0.165613  0.169675   
16  0.249603 -0.135611 -0.128529  0.092906  0.177479  0.032476  0.184397   

        2014      2015      2016      2017      2018      2019  
0   0.034735 -0.243239  0.108990  0.347316 -0.030422  0.304835  
1   0.039185 -0.231932  0.444654  0.726567 -0.179165  0.204403  
2   0.254216  0.120639  0.025639  0.036984  0.022466  0.346565  
3   0.306183  0.283122  0.052467  0.435203 -0.076475  0.427053  
4  -0.122261 -0.118897  0.270549 -0.045640 -0.230799  0.257397  
5   0.452810 -0.032263  0.106119  0.296264  0.037185  0.292457  
6   0.179146  0.006958  0.164676  0.237922 -0.050951  0.075296  
7   0.094869  0.076083  0.379889  0.252079 -0.072443  0.392215  
8   0.057514  0.050180  0.011214  0.142624  0.067230  0.149156  
9   0.001155  0.298259  0.070100  0.448566  0.048030  0.125254  
10  0.219032 -0.061316  0.238501  0.347193 -0.170549 -0.061903  
11  0.173469 -0.045951  0.168431 -0.019407  0.392041  0.150402  
12  0.277493  0.221437  0.175239  0.392602  0.199786  0.523683  
13  0.155352 -0.097075  0.108383  0.129631  0.035732  0.361397  
14  0.040476 -0.145576  0.191249  0.182777 -0.149076  0.443615  
15  0.118167 -0.269737  0.175712  0.462878 -0.039664  0.317488  
16 -0.051128 -0.125672  0.205984 -0.045163 -0.152840  0.076716

In [4]:
performance.shape

(17, 20)

In [5]:
performance = (performance.T)
performance.head()

0         1         2         3         4         5         6   \
2000  0.006869  0.002751  0.000113 -0.331899 -0.240567 -0.277085  0.141905   
2001 -0.339676  0.163384 -0.248466  0.120603  0.438470  0.027439  0.151746   
2002  0.000563 -0.099845 -0.209897 -0.526192 -0.352779 -0.510107 -0.075660   
2003  0.359279  0.851785  0.401704  0.478752  0.185081  1.008141 -0.030887   
2004  0.171095  0.195363  0.205888  0.205863  0.069837 -0.272635  0.251665   

            7         8         9         10        11        12        13  \
2000 -0.044133  0.077278 -0.128416  0.286055  0.388044 -0.630400 -0.259008   
2001 -0.158802 -0.206370 -0.210681  0.021827 -0.356181  0.501246  0.035282   
2002 -0.316161 -0.047961 -0.384196  0.074855 -0.018401 -0.224306  0.109682   
2003  0.503459  0.172817  0.558968  0.406301 -0.128434  0.055847  0.182587   
2004  0.094612 -0.161974  0.308512 -0.017198 -0.317250  0.080927  0.126378   

            14        15        16  
2000  0.274998 -0.219444  0.117179  
2001 -0.158230  0.089313 -0.073265  
2002 -0.028285 -0.119144 -0.088605  
2003  0.545048  0.054353  0.204296  
2004  0.106536 -0.000555  0.279813

In [6]:
performance.shape

(20, 17)

In [89]:
X = performance
print('X ~ n_samples x n_features:', X.shape)
#type(X)

#X = list(X.values)
X = X.to_numpy()
X


# li1 = []
# for index, row in X.iterrows():
#      #print(list(row))
#      li1.append([row])
# li1 = list(X.values)
# X = li1
# li1 = np.array(li1)
# type (li1)
# li1

X ~ n_samples x n_features: (20, 17)


array([[ 6.86869800e-03,  2.75084000e-03,  1.13338000e-04,
        -3.31899206e-01, -2.40566854e-01, -2.77084859e-01,
         1.41905316e-01, -4.41331850e-02,  7.72783430e-02,
        -1.28415672e-01,  2.86055457e-01,  3.88043908e-01,
        -6.30399591e-01, -2.59007921e-01,  2.74997949e-01,
        -2.19443633e-01,  1.17179269e-01],
       [-3.39675651e-01,  1.63384060e-01, -2.48466068e-01,
         1.20602887e-01,  4.38470238e-01,  2.74385300e-02,
         1.51746217e-01, -1.58802277e-01, -2.06370168e-01,
        -2.10680621e-01,  2.18268490e-02, -3.56181240e-01,
         5.01246318e-01,  3.52817220e-02, -1.58229587e-01,
         8.93126860e-02, -7.32651540e-02],
       [ 5.62783000e-04, -9.98454840e-02, -2.09897155e-01,
        -5.26191532e-01, -3.52779026e-01, -5.10106754e-01,
        -7.56595500e-02, -3.16161096e-01, -4.79609900e-02,
        -3.84195762e-01,  7.48552940e-02, -1.84006170e-02,
        -2.24306077e-01,  1.09681510e-01, -2.82852760e-02,
        -1.19144053e-01, -8.8

In [90]:
# # Read the csv file into a pandas DataFrame

# potus = pd.read_csv('../data/potus.csv')
# potus.head()

In [91]:
# # Reformat data
# data = potus.values
# y = data[:, 1]
# y

In [92]:
# from sklearn.preprocessing import LabelEncoder

# # Label-encode data set
# label_encoder = LabelEncoder()
# label_encoder.fit(y)
# encoded_y = label_encoder.transform(y)

In [93]:
# for label, original_class in zip(encoded_y, y):
#     print('Original Class: ' + str(original_class))
#     print('Encoded Label: ' + str(label))
#     print('-' * 12)

In [94]:
# from keras.utils import to_categorical

# # One-hot encoding
# one_hot_y = to_categorical(encoded_y)
# one_hot_y

In [95]:
# Read the csv file into a pandas DataFrame

potus_one_hot = pd.read_csv('../data/potus_one_hot.csv')
potus_one_hot.head()

year       potus  one_hot
0  2000    Democrat        0
1  2001  Republican        1
2  2002  Republican        1
3  2003  Republican        1
4  2004  Republican        1

In [107]:
# Reformat data
data = potus_one_hot.values
y = data[:, 2]
y=y.astype('int')
y.dtype
# y = [[int(i)] for i in y]
# type(y)
# y

dtype('int32')

In [108]:
print('y ~ n_samples:', y.shape)

y ~ n_samples: (20,)


Classification is a supervised task, and since we are interested in its performance on unseen data, we split our data into two parts:

1. a training set that the learning algorithm uses to fit the model
2. a test set to evaluate the generalization performance of the model

The ``train_test_split`` function from the ``model_selection`` module does that for us -- we will use it to split a dataset into 75% training data and 25% test data.

<img src="figures/train_test_split_matrix.svg" width="100%">

In [109]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [110]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScater model and fit it to the training data

X_scaler = StandardScaler().fit(X_train.reshape(-1, 1))
#X_scaler = StandardScaler().fit(X_train)

In [111]:
# Transform the training and testing data using the X_scaler and y_scaler models

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [112]:
# X_train.shape
# type(X_train)

In [113]:
y_train.shape
y_train

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0])

In [114]:
# Loop through different k values to see which has the highest accuracy
# Note: We only use odd numbers because we don't want any ties
train_scores = []
test_scores = []
for k in range(1, 14, 2):
    knn = KNeighborsClassifier(n_neighbors=k)
#    knn.fit(X_train, y_train)
    knn.fit(X_train_scaled, y_train)
    train_score = knn.score(X_train_scaled, y_train)
    test_score = knn.score(X_test_scaled, y_test)
#     train_score = knn.score(X_train, y_train)
#     test_score = knn.score(X_test, y_test)
#     train_scores.append(train_score)
    test_scores.append(test_score)
    print(f"k: {k}, Train/Test Score: {train_score:.3f}/{test_score:.3f}")
    
    
plt.plot(range(1, 20, 2), train_scores, marker='o')
plt.plot(range(1, 20, 2), test_scores, marker="x")
plt.xlabel("k neighbors")
plt.ylabel("Testing accuracy Score")
plt.show()

k: 1, Train/Test Score: 1.000/0.800
k: 3, Train/Test Score: 0.667/0.800
k: 5, Train/Test Score: 0.467/0.600
k: 7, Train/Test Score: 0.467/0.600
k: 9, Train/Test Score: 0.733/0.600
k: 11, Train/Test Score: 0.533/0.400
k: 13, Train/Test Score: 0.600/0.600
k: 15, Train/Test Score: 0.533/0.600


ValueError: Expected n_neighbors <= n_samples,  but n_samples = 15, n_neighbors = 17

In [60]:
# Note that k: 9 provides the best accuracy where the classifier starts to stablize
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train_scaled, y_train)
print('k=9 Test Acc: %.3f' % knn.score(X_test_scaled, y_test))

In [61]:
# print(prediction)
# print(y_test)

[ 2.30695783 -0.73511651 -2.42873363  1.72909751  1.59456586]
[0 0 1 1 1]


We can evaluate our classifier quantitatively by measuring what fraction of predictions is correct. This is called **accuracy**:

In [62]:
# prediction == y_test

array([False, False, False, False, False])

In [63]:
# np.mean(prediction == y_test)

0.0

There is also a convenience function , ``score``, that all scikit-learn classifiers have to compute this directly from the test data:

In [64]:
# classifier.score(X_test, y_test)

-14.419797305516562

It is often helpful to compare the generalization performance (on the test set) to the performance on the training set:

In [65]:
# classifier.score(X_train, y_train)

1.0